CREATE TABLE IF NOT EXISTS contract_templates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  service_type VARCHAR(50) NOT NULL,
  version VARCHAR(50) NOT NULL DEFAULT '1.0',
  body MEDIUMTEXT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'draft',
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  INDEX idx_contract_templates_status (status),
  CONSTRAINT chk_contract_templates_service_type CHECK (service_type IN ('website_kit','website_build','shopify_makeover','website_revamp','custom_service')),
  CONSTRAINT chk_contract_templates_status CHECK (status IN ('draft','active','archived'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  short_description TEXT NOT NULL,
  full_description MEDIUMTEXT NULL,
  service_type VARCHAR(50) NOT NULL,
  fulfillment_type VARCHAR(50) NOT NULL DEFAULT 'service',
  price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  deposit_amount DECIMAL(10,2) NULL,
  turnaround_text TEXT NULL,
  includes_text MEDIUMTEXT NULL,
  requirements_text MEDIUMTEXT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'draft',
  is_featured TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  contract_template_id INT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  INDEX idx_products_public (status, sort_order),
  INDEX idx_products_contract_template (contract_template_id),
  CONSTRAINT chk_products_service_type CHECK (service_type IN ('website_kit','website_build','shopify_makeover','website_revamp','custom_service')),
  CONSTRAINT chk_products_fulfillment_type CHECK (fulfillment_type IN ('service','digital_kit','hybrid')),
  CONSTRAINT chk_products_status CHECK (status IN ('draft','active','archived')),
  CONSTRAINT fk_products_contract_template FOREIGN KEY (contract_template_id) REFERENCES contract_templates(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_number VARCHAR(50) NULL UNIQUE,
  product_id INT NULL,
  customer_name VARCHAR(190) NOT NULL,
  customer_email VARCHAR(190) NOT NULL,
  business_name VARCHAR(190) NULL,
  phone VARCHAR(100) NULL,
  preferred_contact_method VARCHAR(50) NULL,
  website_url VARCHAR(500) NULL,
  project_notes MEDIUMTEXT NULL,
  product_name_snapshot VARCHAR(255) NOT NULL,
  product_price_snapshot DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  service_type_snapshot VARCHAR(50) NOT NULL,
  product_snapshot_json JSON NULL,
  order_status VARCHAR(50) NOT NULL DEFAULT 'pending_contract',
  payment_status VARCHAR(50) NOT NULL DEFAULT 'pending',
  contract_status VARCHAR(50) NOT NULL DEFAULT 'pending',
  admin_notes MEDIUMTEXT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  INDEX idx_orders_email (customer_email),
  INDEX idx_orders_order_status (order_status),
  INDEX idx_orders_contract_status (contract_status),
  INDEX idx_orders_payment_status (payment_status),
  INDEX idx_orders_product (product_id),
  CONSTRAINT fk_orders_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
  CONSTRAINT chk_orders_order_status CHECK (order_status IN ('pending_contract','contract_sent','contract_signed','payment_pending','paid','in_progress','completed','cancelled')),
  CONSTRAINT chk_orders_payment_status CHECK (payment_status IN ('not_required','pending','paid','refunded','failed')),
  CONSTRAINT chk_orders_contract_status CHECK (contract_status IN ('pending','sent','viewed','signed','void'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_instances (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  contract_template_id INT NULL,
  contract_title_snapshot VARCHAR(255) NOT NULL,
  contract_version_snapshot VARCHAR(50) NOT NULL,
  contract_body_snapshot MEDIUMTEXT NOT NULL,
  rendered_contract_snapshot MEDIUMTEXT NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  sent_at DATETIME NULL,
  viewed_at DATETIME NULL,
  signed_at DATETIME NULL,
  signer_legal_name VARCHAR(190) NULL,
  typed_signature VARCHAR(190) NULL,
  signer_ip VARCHAR(100) NULL,
  signer_user_agent VARCHAR(500) NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NULL,
  INDEX idx_contract_instances_order (order_id),
  INDEX idx_contract_instances_status (status),
  CONSTRAINT fk_contract_instances_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_contract_instances_template FOREIGN KEY (contract_template_id) REFERENCES contract_templates(id) ON DELETE SET NULL,
  CONSTRAINT chk_contract_instances_status CHECK (status IN ('pending','sent','viewed','signed','void'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
