-- Phase 2.3: reusable questionnaires, immutable order snapshots, and field-associated uploads.
CREATE TABLE IF NOT EXISTS questionnaire_templates (
 id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, internal_description TEXT NULL, status VARCHAR(50) NOT NULL DEFAULT 'draft', created_at DATETIME NOT NULL, updated_at DATETIME NULL,
 UNIQUE KEY uq_questionnaire_templates_title (title), INDEX idx_questionnaire_templates_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS questionnaire_fields (
 id INT AUTO_INCREMENT PRIMARY KEY, questionnaire_template_id INT NOT NULL, field_key VARCHAR(100) NOT NULL, field_type VARCHAR(50) NOT NULL, label TEXT NOT NULL, admin_label VARCHAR(255) NULL, help_text TEXT NULL, placeholder VARCHAR(500) NULL, options_json JSON NULL, validation_json JSON NULL, is_required TINYINT(1) NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, sort_order INT NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NULL,
 UNIQUE KEY uq_questionnaire_field_key (questionnaire_template_id,field_key), INDEX idx_questionnaire_fields_active_order (questionnaire_template_id,is_active,sort_order,id), CONSTRAINT fk_questionnaire_fields_template FOREIGN KEY (questionnaire_template_id) REFERENCES questionnaire_templates(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE products ADD COLUMN questionnaire_template_id INT NULL AFTER contract_template_id, ADD INDEX idx_products_questionnaire_template (questionnaire_template_id), ADD CONSTRAINT fk_products_questionnaire_template FOREIGN KEY (questionnaire_template_id) REFERENCES questionnaire_templates(id) ON DELETE SET NULL;
CREATE TABLE IF NOT EXISTS order_questionnaire_snapshots (
 id INT AUTO_INCREMENT PRIMARY KEY, order_id INT NOT NULL, questionnaire_template_id INT NULL, questionnaire_title VARCHAR(255) NOT NULL, questionnaire_snapshot_json JSON NOT NULL, created_at DATETIME NOT NULL, UNIQUE KEY uq_order_questionnaire_snapshot_order (order_id), INDEX idx_oqs_template (questionnaire_template_id), CONSTRAINT fk_oqs_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE, CONSTRAINT fk_oqs_template FOREIGN KEY (questionnaire_template_id) REFERENCES questionnaire_templates(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS order_questionnaire_answers (
 id INT AUTO_INCREMENT PRIMARY KEY, order_id INT NOT NULL, questionnaire_snapshot_id INT NOT NULL, field_key VARCHAR(100) NOT NULL, field_type VARCHAR(50) NOT NULL, question_label TEXT NOT NULL, answer_text MEDIUMTEXT NULL, answer_json JSON NULL, sort_order INT NOT NULL, created_at DATETIME NOT NULL, UNIQUE KEY uq_oqa_snapshot_field (questionnaire_snapshot_id,field_key), INDEX idx_oqa_order_order (order_id,sort_order,id), CONSTRAINT fk_oqa_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE, CONSTRAINT fk_oqa_snapshot FOREIGN KEY (questionnaire_snapshot_id) REFERENCES order_questionnaire_snapshots(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE order_uploads ADD COLUMN questionnaire_field_key VARCHAR(100) NULL AFTER upload_type, ADD COLUMN questionnaire_answer_id INT NULL AFTER questionnaire_field_key, ADD INDEX idx_order_uploads_questionnaire (order_id,questionnaire_field_key), ADD CONSTRAINT fk_order_uploads_questionnaire_answer FOREIGN KEY (questionnaire_answer_id) REFERENCES order_questionnaire_answers(id) ON DELETE SET NULL;
INSERT INTO questionnaire_templates (title,internal_description,status,created_at,updated_at) SELECT 'Standard Shopify Revamp Questionnaire','Migrated from the Phase 2.2 public Shopify Revamp intake form.','active',NOW(),NOW() WHERE NOT EXISTS (SELECT 1 FROM questionnaire_templates WHERE title='Standard Shopify Revamp Questionnaire');
SET @questionnaire_id=(SELECT id FROM questionnaire_templates WHERE title='Standard Shopify Revamp Questionnaire' LIMIT 1);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'store_details','section_heading','Store access and details',NULL,NULL,NULL,0,1,10,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'shopify_store_url','url','What is your Shopify URL?','Your Shopify link is usually similar to username.myshopify.com.',NULL,'{"max_length":500}',1,1,20,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'shopify_collaborator_code','short_text','Shopify Collaborator Request Code','Go to Settings → Users → Security, then scroll down to find the 4 digit code.',NULL,'{"min_length":4,"max_length":4,"pattern":"^[0-9]{4}$"}',1,1,30,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'shopify_password_warning','information','Do not enter your Shopify admin password. Diesel Designs only needs the collaborator request code so access can be requested safely through Shopify.',NULL,NULL,NULL,0,1,40,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'logo_files','multiple_files','Upload your logo(s)','PNG preferred. Please upload high-quality logo files with a transparent background when possible. Diesel Designs will not edit logos unless discussed and paid for before the project.',NULL,'{"allowed_extensions":["png","jpg","jpeg","webp","pdf"],"max_file_count":10,"max_file_size":15728640}',1,1,50,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'homepage','section_heading','Homepage content',NULL,NULL,NULL,0,1,60,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'top_bar_text','short_text','What text would you like in the thin bar at the very top of the website?','Example: Welcome to the store, free shipping, or a short announcement.',NULL,'{"max_length":190}',0,1,70,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'scrolling_banner_text','short_text','Scrolling banner text','Use “-” between phrases. Example: Welcome - Free shipping. Maximum of 2 phrases. Put N/A if you do not want the scrolling text banner.',NULL,'{"max_length":190,"max_dash_phrases":2}',1,1,80,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'featured_collections','long_text','Do you have any collections you''d like featured on the home page? If yes, what are they?',NULL,NULL,NULL,0,1,90,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'featured_products','long_text','Do you have any specific products you want featured on the home page? If so, what are they?',NULL,NULL,NULL,0,1,100,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'collections','section_heading','Collections and reviews',NULL,NULL,NULL,0,1,110,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'new_products_collection','short_text','What is the name of your collection for NEW products?','If you do not have a collection for this yet, please create one first and then put the name of the collection in this field. Example: New Releases.',NULL,'{"max_length":190}',1,1,120,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'trending_products_collection','short_text','What is the name of your collection for TRENDING / POPULAR / HOT products?','If you do not have a collection for this yet, please create one first and then put the name of the collection in this field.',NULL,'{"max_length":190}',1,1,130,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'collection_cover_names','long_text','Please list the categories or product collection names you would like collection cover images created for.','Your order includes up to 20 collection cover images. Additional collection covers are $2 each and must be discussed and paid for before submitting this form.',NULL,NULL,1,1,140,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'reviews_app','long_text','Do you have a reviews app installed and want reviews displayed on your homepage?','Include the app name if yes. Note: Diesel Designs does not install apps as part of this order.',NULL,NULL,0,1,150,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_templates (title,internal_description,status,created_at,updated_at) SELECT 'Custom Shopify Theme Questionnaire','Initial Phase 2.3 custom Shopify theme intake. Review and activate only after assigning the correct contract.','draft',NOW(),NOW() WHERE NOT EXISTS (SELECT 1 FROM questionnaire_templates WHERE title='Custom Shopify Theme Questionnaire');
SET @questionnaire_id=(SELECT id FROM questionnaire_templates WHERE title='Custom Shopify Theme Questionnaire' LIMIT 1);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'business_store_information','section_heading','Business and Store Information',NULL,NULL,NULL,0,1,10,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'business_name','short_text','Business name',NULL,NULL,NULL,1,1,20,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'customer_name','short_text','Customer name',NULL,NULL,NULL,1,1,30,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'customer_email','email','Customer email',NULL,NULL,NULL,1,1,40,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'current_shopify_store_url','url','Current Shopify store URL',NULL,NULL,NULL,0,1,50,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'shopify_store_name','short_text','Shopify store name',NULL,NULL,NULL,1,1,60,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'custom_theme_goal','long_text','What is the main goal for your custom theme?',NULL,NULL,NULL,1,1,70,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'target_audience','long_text','Who is your target audience?',NULL,NULL,NULL,1,1,80,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'products_services_sold','long_text','What products or services do you sell?',NULL,NULL,NULL,1,1,90,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'brand_design_direction','section_heading','Brand and Design Direction',NULL,NULL,NULL,0,1,100,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'brand_aesthetic','long_text','Describe your brand style or aesthetic.',NULL,NULL,NULL,1,1,110,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'brand_colors','short_text','What are your brand colors?',NULL,NULL,NULL,0,1,120,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'font_preferences','short_text','Do you have font preferences?',NULL,NULL,NULL,0,1,130,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'existing_brand_assets','yes_no','Do you have an existing logo and brand assets?',NULL,NULL,NULL,1,1,140,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'brand_asset_upload','multiple_files','Upload your logo and brand assets.',NULL,NULL,'{"allowed_extensions":["png","jpg","jpeg","webp","pdf"],"max_file_count":10,"max_file_size":15728640}',0,1,150,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'inspiration_links','long_text','Share inspiration links.',NULL,NULL,NULL,0,1,160,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'inspiration_uploads','multiple_files','Upload inspiration images or documents.',NULL,NULL,'{"allowed_extensions":["png","jpg","jpeg","webp","pdf"],"max_file_count":10,"max_file_size":15728640}',0,1,170,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'design_elements_to_avoid','long_text','What styles, colors, or elements should we avoid?',NULL,NULL,NULL,0,1,180,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'competitor_inspiration','long_text','Share competitor or industry inspiration.',NULL,NULL,NULL,0,1,190,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'store_content_layout','section_heading','Store Content and Layout',NULL,NULL,NULL,0,1,200,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'featured_products_collections','long_text','Which products or collections should be featured?',NULL,NULL,NULL,0,1,210,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'homepage_sections','checkboxes','Which homepage sections would you like?',NULL,'["Hero banner","Featured collections","Featured products","Testimonials or reviews","Newsletter signup","About the brand","Instagram or social feed","Other"]',NULL,0,1,220,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'navigation_preferences','long_text','Describe your navigation preferences.',NULL,NULL,NULL,0,1,230,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'required_pages','checkboxes','Which pages are required?',NULL,'["Home","About","Contact","FAQ","Shipping and returns","Privacy policy","Terms","Other"]',NULL,0,1,240,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'banner_requirements','long_text','Describe your banner requirements.',NULL,NULL,NULL,0,1,250,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'collection_cover_requirements','long_text','Describe your collection-cover requirements.',NULL,NULL,NULL,0,1,260,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'product_photography_ready','yes_no','Is your product photography ready?',NULL,NULL,NULL,1,1,270,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'existing_graphics_ready','yes_no','Are your existing graphics ready?',NULL,NULL,NULL,1,1,280,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'written_content_ready','dropdown','How ready is your written content?',NULL,'["Ready now","Partially ready","Not started"]',NULL,1,1,290,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'promotion_needs','long_text','Describe announcement-bar or promotional needs.',NULL,NULL,NULL,0,1,300,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'functionality','section_heading','Functionality',NULL,NULL,NULL,0,1,310,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'special_functionality','long_text','Describe any special functionality requests.',NULL,NULL,NULL,0,1,320,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'app_information','long_text','Share app-related information or concerns.',NULL,NULL,NULL,0,1,330,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'existing_shopify_apps','long_text','Which Shopify apps are currently installed?',NULL,NULL,NULL,0,1,340,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'customer_accounts','radio','What customer-account experience is required?',NULL,'["Not needed","Standard Shopify accounts","New customer accounts","Not sure"]',NULL,0,1,350,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'newsletter_signup','yes_no','Do you need newsletter or email signup?',NULL,NULL,NULL,0,1,360,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'forms_needed','long_text','What forms are needed?',NULL,NULL,NULL,0,1,370,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'technical_requirements','long_text','List any other technical requirements.',NULL,NULL,NULL,0,1,380,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'timing_responsibilities','section_heading','Timing, Responsibilities, and Notes',NULL,NULL,NULL,0,1,390,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'desired_launch_date','date','Desired launch timing',NULL,NULL,NULL,0,1,400,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'additional_notes','long_text','Additional notes',NULL,NULL,NULL,0,1,410,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'scope_confirmation','checkboxes','Scope confirmation',NULL,'["I understand work outside the agreed scope may require a separate quote."]',NULL,1,1,420,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'customer_responsibility_confirmation','checkboxes','Customer responsibility confirmation',NULL,'["I will provide required access, feedback, assets, and approvals on time."]',NULL,1,1,430,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'content_readiness_acknowledgement','checkboxes','Content-readiness acknowledgement',NULL,'["I understand missing content may affect the project timeline."]',NULL,1,1,440,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at) VALUES (@questionnaire_id,'final_acknowledgement','yes_no','I confirm the information above is accurate and ready for Diesel Designs to review.',NULL,NULL,NULL,1,1,450,NOW(),NOW()) ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
-- Exercise the single-file control separately from the multiple brand-assets field.
SET @questionnaire_id=(SELECT id FROM questionnaire_templates WHERE title='Custom Shopify Theme Questionnaire' LIMIT 1);
INSERT INTO questionnaire_fields (questionnaire_template_id,field_key,field_type,label,help_text,options_json,validation_json,is_required,is_active,sort_order,created_at,updated_at)
VALUES (@questionnaire_id,'primary_logo_file','file','Upload your primary logo file.','Upload the primary logo separately when one is available.',NULL,'{"allowed_extensions":["png","jpg","jpeg","webp","pdf"],"max_file_count":1,"max_file_size":15728640}',0,1,115,NOW(),NOW())
ON DUPLICATE KEY UPDATE field_key=VALUES(field_key);
